import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "../globals.css";
import "../styles/globals.css";
import PageHeader from "./components/header";
import PageFooter from "./components/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
const nunito = Nunito({
    variable: "--font-nunito-sans",
    display: "swap",
    weight: ["300", "400", "600", "700","800", "900"],
    subsets: ["latin"],
  });

export const metadata = {
    title: "Login",
    description: "Generated by create next app",
};

export default function PageLayout({ children }) {
    return (
        <div>
            <PageHeader /> {/* Add the Header component */}
            {children} {/* Render the page content */}
            <PageFooter /> {/* Add the Footer component */}
        </div>
    );
}